// +build windows,amd64

// Code generated by "go run github.com/tg123/fabric/mkidl"; DO NOT EDIT.
package fabric

import (
	"syscall"
	"unsafe"
)

func boolToUintptr(x bool) uintptr {
	if x {
		return 1
	}
	return 0
}
func callStub1(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		0,
		0,
	)
	return hr, err
}
func callStub96862646(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub142410278(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub142934571(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub328735686(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 float64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub571021482(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub642392001(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub667092344(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricMoveCost,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub699991442(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub765140102(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub765920742(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricFaultType,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub770250917(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub824512273(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub877275087(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub1072500600(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 bool,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		boolToUintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub1121783681(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub1128800280(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricStoreBackupOption,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub1238898970(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub1258170961(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		uintptr(argv7),
	)
	return hr, err
}
func callStub1292376406(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaOpenMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub1425410019(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
	)
	return hr, err
}
func callStub1522013493(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		boolToUintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub1580995785(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub1789138364(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaSetQuorumMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub2138378508(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub2823758008(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 int64,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub2844134223(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
	)
	return hr, err
}
func callStub2876708553(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub2937459220(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaRole,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub3260095110(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub3312394536(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub3398245106(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		boolToUintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub3415612146(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		boolToUintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub3552647931(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub3634565860(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		boolToUintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub3653833453(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub3654885027(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricNodeDeactivationIntent,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub3657439995(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub3758625517(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub3857978088(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub3858959655(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		boolToUintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub3863417581(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub3886746928(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub3964606417(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricReplicaRole,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub3992725221(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		uintptr(argv7),
	)
	return hr, err
}
func callStub4048098088(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 FabricErrorCode,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub4076149611(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub4095221463(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub4096331056(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub4101645460(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub4120646493(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub4152495520(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func createCallbackStub1(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub699991442(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub2138378508(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub2823758008(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub2844134223(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
