// +build windows,amd64

// Code generated by "go run github.com/tg123/fabric/mkidl"; DO NOT EDIT.
package fabric

import (
	"syscall"
	"unsafe"
)

func boolToUintptr(x bool) uintptr {
	if x {
		return 1
	}
	return 0
}
func callStub1(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub2(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
	)
	return hr, err
}
func callStub3(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub5(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 int64,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub10(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub11(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		0,
		0,
	)
	return hr, err
}
func callStub12(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
	)
	return hr, err
}
func callStub13(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricFaultType,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub14(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricMoveCost,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub15(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaOpenMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub16(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaRole,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub17(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub18(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub19(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub20(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricReplicaRole,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub21(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaSetQuorumMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub22(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub23(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub24(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub25(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub26(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub27(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub28(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub29(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub30(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricStoreBackupOption,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub31(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub32(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub33(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub34(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		boolToUintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub35(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		boolToUintptr(argv1),
		uintptr(argv2),
		0,
		0,
	)
	return hr, err
}
func callStub36(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub37(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint64,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub38(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
) (uintptr, error) {
	hr, _, err := syscall.Syscall(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		0,
	)
	return hr, err
}
func callStub39(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		boolToUintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub40(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub41(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub42(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 float64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub43(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub44(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub45(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		boolToUintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub46(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		uintptr(argv7),
	)
	return hr, err
}
func callStub47(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub48(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub49(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub50(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		uintptr(argv7),
	)
	return hr, err
}
func callStub51(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricNodeDeactivationIntent,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub52(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func callStub53(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 bool,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		boolToUintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub54(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		0,
		0,
	)
	return hr, err
}
func callStub55(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall9(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
		uintptr(argv5),
		uintptr(argv6),
		0,
	)
	return hr, err
}
func callStub56(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 FabricErrorCode,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		uintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		0,
	)
	return hr, err
}
func callStub57(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	hr, _, err := syscall.Syscall6(
		addr,
		uintptr(argc+1),
		uintptr(this),
		uintptr(argv0),
		boolToUintptr(argv1),
		uintptr(argv2),
		uintptr(argv3),
		uintptr(argv4),
	)
	return hr, err
}
func createCallbackStub4(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub6(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub7(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub8(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
func createCallbackStub9(
	cb interface{},
) uintptr {
	return syscall.NewCallback(cb)
}
