// +build linux,amd64

// Code generated by "go run github.com/tg123/fabric/mkidl"; DO NOT EDIT.
package fabric

import (
	"unsafe"
)

func callStub1048489181713478054(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1335730304632643656(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1533526493275071680(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub1630288334828793287(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1819859077681302979(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2075713109747488783(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint64,
) (uintptr, error) {
	panic("not impl")
}
func callStub2165927519712776285(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2483127582336966541(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaOpenMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2882371996775522769(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub3094878924190377857(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricStoreBackupOption,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3185167729122897081(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3547117239461852141(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4161178164818170091(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4405830402697095593(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricReplicaRole,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4555919410121256920(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub5789215629241811153(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 FabricErrorCode,
) (uintptr, error) {
	panic("not impl")
}
func callStub5955222752708360228(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub6142135466863627413(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub6419494709900638139(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricFaultType,
) (uintptr, error) {
	panic("not impl")
}
func callStub7287933853701551490(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub7503403356184589199(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub7782600151265676089(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub8271036529602806980(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub9429292076469177682(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub9532067423886724566(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub9554407596381520368(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub9660077576991986601(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub9707163627877372518(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub10058214422621334751(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub10107670971298011941(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub11099145478811451011(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub11563507578962675232(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub11945374741807581896(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricMoveCost,
) (uintptr, error) {
	panic("not impl")
}
func callStub12358644010272102580(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub12664629900598883453(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 float64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub13310073979949236625(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub13385571198022537309(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub14727739111527231414(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub15208723179229678737(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaRole,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub15487510995445485658(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub15598723421636958591(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub15718182357955102547(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
) (uintptr, error) {
	panic("not impl")
}
func callStub15738012513523528246(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub15846046096096524420(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 bool,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub15865859949363472529(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub16087644903281589486(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaSetQuorumMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub17177410701984374373(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricNodeDeactivationIntent,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub17244673165462293359(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub17320848538307195614(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub17813239524112400266(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub18124872607643347555(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 int64,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub18391797109609713916(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func createCallbackStub9488618411548846275(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub12380892614712961058(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub13508278033908553326(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub15030901481496332800(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub15268508920543171926(
	cb interface{},
) uintptr {
	panic("not impl")
}
