//go:build !windows && !linux && !amd64 && !cgo
// +build !windows,!linux,!amd64,!cgo

// Code generated by "go run github.com/tg123/fabric/mkidl"; DO NOT EDIT.
package fabric

import (
	"github.com/go-ole/go-ole"
	"unsafe"
)

func callStub1(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub10168106(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *uint16,
	argv3 uint32,
	argv4 *byte,
	argv5 uint32,
	argv6 *comFabricAsyncOperationCallback,
	argv7 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub12982384(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetNetworkListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub33038035(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageActivationContext,
	argv1 *comFabricDataPackage,
	argv2 *comFabricDataPackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub36708053(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageActivationContext,
	argv1 *comFabricCodePackage,
	argv2 *comFabricCodePackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub58404487(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStartPartitionQuorumLossDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub68954620(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *innerFabricNetworkDescription,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub83231191(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *bool,
) (uintptr, error) {
	panic("not impl")
}
func callStub95161944(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricServiceGroupFactoryBuilder,
) (uintptr, error) {
	panic("not impl")
}
func callStub96862646(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub113443296(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub125246569(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricChaosScheduleDescriptionResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub128461894(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *innerFabricServiceUpdateDescription,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub142410278(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
) (uintptr, error) {
	panic("not impl")
}
func callStub142934571(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint64,
) (uintptr, error) {
	panic("not impl")
}
func callStub161743442(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
) (uintptr, error) {
	panic("not impl")
}
func callStub183829116(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **uint16,
) (uintptr, error) {
	panic("not impl")
}
func callStub192030626(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricSecretReferenceList,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub196420147(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 int64,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub202642428(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricOperation,
) (uintptr, error) {
	panic("not impl")
}
func callStub204024326(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricMoveSecondaryDescription2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub206897835(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *float64,
) (uintptr, error) {
	panic("not impl")
}
func callStub213847623(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 *bool,
) (uintptr, error) {
	panic("not impl")
}
func callStub237241026(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *ole.GUID,
) (uintptr, error) {
	panic("not impl")
}
func callStub239278236(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 **comFabricKeyValueStoreItemEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub256646334(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricPartitionRestartProgressResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub261819996(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **comFabricConfigurationPackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub277424671(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricGetChaosReportDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub280113323(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedApplicationHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub317597625(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricClusterHealthPolicy,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub324473949(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **comFabricKeyValueStoreItemMetadataEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub349841345(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStopNodeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub351017874(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 uint32,
	argv3 *byte,
	argv4 ole.GUID,
	argv5 int64,
	argv6 **comFabricStatelessServiceInstance,
) (uintptr, error) {
	panic("not impl")
}
func callStub353513122(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerPagedFabricApplicationTypeQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub358945863(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 **innerFabricConfigurationParameterList,
) (uintptr, error) {
	panic("not impl")
}
func callStub361701325(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedNetworkCodePackageListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub446699738(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricPartitionHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub452726352(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 *int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub456925103(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricEpoch,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub469248570(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRestartReplicaDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub483535990(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricApplicationUpgradeProgressResult2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub504377011(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceNotificationFilterDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub507128961(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricChaosServiceScheduleDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub519645766(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricNodeTransitionDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub519835320(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint32,
	argv1 **innerFabricOperationDataBuffer,
) (uintptr, error) {
	panic("not impl")
}
func callStub540480608(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricReplicator,
) (uintptr, error) {
	panic("not impl")
}
func callStub555091076(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint32,
	argv1 **byte,
) (uintptr, error) {
	panic("not impl")
}
func callStub568797750(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *innerFabricClusterHealthPolicy,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub569056432(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetReplicaLoadInformationResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub575545299(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricUpgradeProgressResult,
	argv1 *uint32,
	argv2 **innerFabricUpgradeDomainStatusDescription,
) (uintptr, error) {
	panic("not impl")
}
func callStub577637937(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 *bool,
) (uintptr, error) {
	panic("not impl")
}
func callStub591269392(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub607330252(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaRole,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub607984828(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetServiceGroupMemberListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub618732754(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetClusterLoadInformationResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub637082826(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricDeployedApplicationHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub637800223(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricStatefulServiceFactory,
) (uintptr, error) {
	panic("not impl")
}
func callStub638196964(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetApplicationNetworkListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub644099186(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStringList,
	argv1 *innerFabricStringMap,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub653008100(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetNetworkApplicationListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub657523919(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
) (uintptr, error) {
	panic("not impl")
}
func callStub667092344(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricMoveCost,
) (uintptr, error) {
	panic("not impl")
}
func callStub676928756(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricPartitionDataLossProgressResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub698100896(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationNameQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub708974790(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 *comFabricOperationDataStream,
	argv2 **comFabricOperationDataStream,
) (uintptr, error) {
	panic("not impl")
}
func callStub719329543(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationCallback,
	argv1 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub765920742(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricFaultType,
) (uintptr, error) {
	panic("not impl")
}
func callStub797714419(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStopNodeDescription2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub805965666(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **innerFabricConfigurationSection,
) (uintptr, error) {
	panic("not impl")
}
func callStub834738492(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricChaosDescriptionResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub843716914(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricSecretReferencesResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub848435520(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetPartitionListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub858073090(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricUpgradeProgressResult2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub867244313(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricUpgradeProgressResult2,
) (uintptr, error) {
	panic("not impl")
}
func callStub870067387(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricPartitionHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub891230544(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricPropertyMetadataResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub895233792(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaOpenMode,
	argv1 *comFabricStatefulServicePartition,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub897264833(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationTypeQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub906170255(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricStatelessServiceFactory,
) (uintptr, error) {
	panic("not impl")
}
func callStub917576855(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 **comFabricKeyValueStoreItemMetadataResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub918105284(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricClusterManifestQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub923865033(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **innerFabricServicePartitionInformation,
) (uintptr, error) {
	panic("not impl")
}
func callStub934293207(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRestartDeployedCodePackageDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub945303794(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedNetworkCodePackageQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub954674379(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedNetworkQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub955057789(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricEpoch,
) (uintptr, error) {
	panic("not impl")
}
func callStub959650155(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricHealthInformation,
	argv1 *innerFabricHealthReportSendOptions,
) (uintptr, error) {
	panic("not impl")
}
func callStub969350345(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 int64,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub988024610(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricServiceEndpointsVersion,
	argv1 *int32,
) (uintptr, error) {
	panic("not impl")
}
func callStub1017847011(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedCodePackageListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1029384839(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricNodeHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1038946022(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricDataPackageChangeHandler,
	argv1 *int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub1041370855(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageChangeHandler,
	argv1 *int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub1058809897(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStartNodeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1074540738(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *uint16,
	argv3 *innerFabricApplicationHealthPolicy,
	argv4 uint32,
	argv5 *comFabricAsyncOperationCallback,
	argv6 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1078136600(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageEventHandler,
	argv1 *uint64,
) (uintptr, error) {
	panic("not impl")
}
func callStub1093478449(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricNodeQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1095441712(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedApplicationListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1100491408(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricTestCommandListDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1102585135(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedServiceTypeListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1162682386(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 bool,
	argv3 **comFabricKeyValueStoreItemMetadataEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub1174610639(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *uint16,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1188245789(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricUnplacedReplicaInformationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1193945761(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRepairTaskQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1219894651(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricOrchestrationUpgradeStatusResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1235163516(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetRepairTaskListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1241198885(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationLoadInformationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1252332865(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricStringResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1271142804(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricApplicationHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1283856813(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricTestCommandStatusResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1319774882(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricStatefulServiceFactory,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1371020529(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 bool,
	argv3 **comFabricKeyValueStoreItemEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub1422533374(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 float64,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1453659128(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 int32,
	argv3 *byte,
	argv4 int64,
	argv5 *bool,
) (uintptr, error) {
	panic("not impl")
}
func callStub1460346160(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 bool,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1487275852(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *uint16,
) (uintptr, error) {
	panic("not impl")
}
func callStub1501048585(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRestartDeployedCodePackageDescription2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1510606945(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricTransaction,
) (uintptr, error) {
	panic("not impl")
}
func callStub1513498715(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStartNodeDescription2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1530862905(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1547050227(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 *comFabricAsyncOperationCallback,
	argv2 *int64,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1579621757(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetApplicationTypePagedListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1583356278(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 **comFabricKeyValueStoreItemResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1591353426(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1602229622(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricOperationData,
) (uintptr, error) {
	panic("not impl")
}
func callStub1604588963(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricSecretsResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1614547105(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStringList,
) (uintptr, error) {
	panic("not impl")
}
func callStub1618419114(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetPartitionLoadInformationResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1658396045(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricApplicationUpgradeProgressResult2,
) (uintptr, error) {
	panic("not impl")
}
func callStub1659701457(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricStringResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1667310452(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaSetQuorumMode,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1672813023(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetApplicationNameResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1686247930(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetApplicationListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1692408320(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricChaosEventsSegmentResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1693391353(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetServiceTypeListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1695029750(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetNetworkNodeListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1730288159(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricServiceDescriptionResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1734815575(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricUnprovisionApplicationTypeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1754078723(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricPartitionQuorumLossProgressResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub1770270006(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServicePartitionQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1770596497(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStartChaosDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1851403586(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStartPartitionRestartDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1884367613(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceNameQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1900677472(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricHealthReport,
) (uintptr, error) {
	panic("not impl")
}
func callStub1919561566(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedServicePackageQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1952916287(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *ole.GUID,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub1956780580(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricKeyValueStoreTransactionSettings,
	argv1 **comFabricTransaction,
) (uintptr, error) {
	panic("not impl")
}
func callStub1992503670(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 FabricStoreBackupOption,
	argv2 *comFabricStorePostBackupHandler,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2005544817(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricReplicaLoadInformationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2044014450(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedServiceReplicaQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2053317551(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStoreBackupInfo,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2056525365(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 bool,
	argv2 **comFabricKeyValueStoreItemMetadataEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub2069637915(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricNetworkNodeQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2081565471(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2083531550(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceTypeQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2084117971(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricDeployedServicePackageHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2087791960(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *innerFabricPutCustomPropertyOperation,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2104103228(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **comFabricKeyValueStoreItemEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub2106724373(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 int32,
	argv3 *byte,
) (uintptr, error) {
	panic("not impl")
}
func callStub2107052050(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 int64,
	argv3 *bool,
) (uintptr, error) {
	panic("not impl")
}
func callStub2123967250(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricStatelessServiceFactory,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2135951864(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricOperationStream,
) (uintptr, error) {
	panic("not impl")
}
func callStub2148609923(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceGroupMemberTypeQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2212636154(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 *comFabricOperationData,
	argv2 *comFabricAsyncOperationCallback,
	argv3 *int64,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2242251326(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricClientSettings,
) (uintptr, error) {
	panic("not impl")
}
func callStub2309098093(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricStringListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2312383861(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2313561743(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageActivationContext,
	argv1 *comFabricConfigurationPackage,
	argv2 *comFabricConfigurationPackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub2336501662(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricProvisionedCodeVersionQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2342067669(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2355046004(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricEpoch,
	argv1 FabricReplicaRole,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2356948344(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStartPartitionDataLossDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2378902330(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricCancelTestCommandDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2425950701(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricKeyValueStoreNotificationEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub2480277880(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *bool,
	argv3 **uint16,
) (uintptr, error) {
	panic("not impl")
}
func callStub2539399424(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRestartNodeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2551388847(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageActivationContext,
	argv1 *comFabricConfigurationPackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub2564365881(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedServicePackageListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2577805748(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedServicePackageHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2579049308(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeleteApplicationDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2580293897(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2580880988(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetUnplacedReplicaInformationResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2590318180(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetApplicationLoadInformationResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2592672382(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **comFabricDataPackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub2593786495(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **comFabricCodePackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub2601852510(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetServiceGroupMemberTypeListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2628324035(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 *innerFabricLoadMetric,
) (uintptr, error) {
	panic("not impl")
}
func callStub2635018164(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRepairTaskHealthPolicyUpdateDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2649955961(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetProvisionedCodeVersionListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2689210022(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricNodeHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2692690373(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedServiceReplicaDetailQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2693868396(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationUpdateDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2727616027(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 ole.GUID,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2776959849(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricServiceNotification,
) (uintptr, error) {
	panic("not impl")
}
func callStub2781881351(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRepairTask,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2782464874(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricHealthInformation,
) (uintptr, error) {
	panic("not impl")
}
func callStub2786667429(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *innerFabricKeyValueStoreRestoreSettings,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2791051842(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **innerFabricEndpointResourceDescription,
) (uintptr, error) {
	panic("not impl")
}
func callStub2809997595(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 FabricNodeDeactivationIntent,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2819431147(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageActivator,
	argv1 *innerFabricCodePackageEventDescription,
) (uintptr, error) {
	panic("not impl")
}
func callStub2823424846(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 **comFabricStringResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub2840077331(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricSecretList,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2849508210(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricOperationDataStream,
) (uintptr, error) {
	panic("not impl")
}
func callStub2851408785(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricServiceGroupFactory,
) (uintptr, error) {
	panic("not impl")
}
func callStub2879064828(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *ole.GUID,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2896763624(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub2897223226(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 **comFabricKeyValueStoreItemMetadataEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub2933269540(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStringList,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3008178482(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRestartNodeDescription2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3011972084(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricReplicatorSettings,
) (uintptr, error) {
	panic("not impl")
}
func callStub3015846206(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRepairCancelDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3016760091(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetClusterHealthChunkResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3021346513(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageActivationContext,
	argv1 *comFabricDataPackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub3022460626(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricCodePackageActivationContext,
	argv1 *comFabricCodePackage,
) (uintptr, error) {
	panic("not impl")
}
func callStub3052276746(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricClientSettingsResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3058897413(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricResolvedServicePartitionResult,
	argv1 *int32,
) (uintptr, error) {
	panic("not impl")
}
func callStub3070498572(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetNodeListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3090491723(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRepairDeleteDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3091278146(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricMovePrimaryDescription2,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3096647476(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricChaosReportResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3099340783(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricProvisionApplicationTypeDescriptionBase,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3113496028(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricClusterHealthChunkQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3116898117(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricMovePrimaryResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3140294497(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricHealthReport,
	argv1 *innerFabricHealthReportSendOptions,
) (uintptr, error) {
	panic("not impl")
}
func callStub3147836897(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceGroupMemberQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3172535365(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3213436593(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 *comFabricServicePartitionResolutionChangeHandler,
	argv4 *int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub3220048980(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricSecurityCredentials,
) (uintptr, error) {
	panic("not impl")
}
func callStub3267176230(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricStatelessServicePartition,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3287558507(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricStartUpgradeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3304399248(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricEpoch,
	argv1 int64,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3319082455(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 uint32,
	argv2 *innerFabricPropertyBatchOperation,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3325831539(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceGroupDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3333893057(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricReplicaHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3342216692(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 bool,
	argv2 *comFabricPropertyEnumerationResult,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3351979033(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricOperationData,
	argv1 *comFabricAsyncOperationCallback,
	argv2 *int64,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3353025305(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 **comFabricKeyValueStoreItemEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub3357944167(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricServiceGroupFactory,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3377670524(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3385142793(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationNetworkQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3391564747(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricChaosEventsSegmentDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3399953929(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricNetworkApplicationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3410640052(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 *comFabricResolvedServicePartitionResult,
	argv4 uint32,
	argv5 *comFabricAsyncOperationCallback,
	argv6 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3426753368(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3433896822(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetNodeLoadInformationResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3443731410(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3449236433(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationUpgradeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3458927767(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricAsyncOperationCallback,
) (uintptr, error) {
	panic("not impl")
}
func callStub3466992508(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedReplicaListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3495041948(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetApplicationTypeListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3500678054(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedNetworkListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3525650837(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricNetworkQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3530238920(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *innerFabricApplicationHealthPolicy,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3543805448(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedCodePackageQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3548457955(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricClusterHealthQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3550488954(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricSecretReferenceList,
	argv1 bool,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3551337424(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricNodeTransitionProgressResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3577164681(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *uint16,
	argv3 *innerFabricPackageSharingPolicyList,
	argv4 *uint16,
	argv5 uint32,
	argv6 *comFabricAsyncOperationCallback,
	argv7 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3583053062(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricKeyValueStoreEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub3588690708(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 bool,
	argv2 **comFabricKeyValueStoreItemEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub3597872623(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 ole.GUID,
	argv1 int64,
	argv2 *innerFabricApplicationHealthPolicy,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3603111684(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedServiceReplicaDetailResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3604295734(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricPagedDeployedApplicationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3606388497(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetDeployedApplicationPagedListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3636403076(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3686276047(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricReplicaSetConfiguration,
	argv1 *innerFabricReplicaSetConfiguration,
) (uintptr, error) {
	panic("not impl")
}
func callStub3692106587(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint32,
	argv1 **innerFabricUpgradeDomainStatusDescription,
) (uintptr, error) {
	panic("not impl")
}
func callStub3703377222(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricServiceEndpointsVersion,
) (uintptr, error) {
	panic("not impl")
}
func callStub3704758100(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetProvisionedConfigVersionListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3716160173(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 uint32,
	argv3 *byte,
	argv4 ole.GUID,
	argv5 int64,
	argv6 **comFabricStatefulServiceReplica,
) (uintptr, error) {
	panic("not impl")
}
func callStub3743488957(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 **comFabricKeyValueStoreItemMetadataEnumerator,
) (uintptr, error) {
	panic("not impl")
}
func callStub3809816119(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricNodeLoadInformationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3825799703(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 int32,
	argv3 *byte,
	argv4 *bool,
) (uintptr, error) {
	panic("not impl")
}
func callStub3830844808(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricGatewayInformationResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3839431158(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricTransactionBase,
	argv1 *uint16,
	argv2 int32,
	argv3 *byte,
	argv4 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub3842780724(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricApplicationUpgradeUpdateDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3856476601(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeleteServiceDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3876526048(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricReplicaHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3893893105(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricServiceHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3899200196(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricConfigurationPackageChangeHandler,
	argv1 *int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub3902740489(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricMoveSecondaryResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3906148354(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricClusterHealthResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3908577728(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricUpgradeUpdateDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3927910851(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRemoveReplicaDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3929351393(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricServiceManagementClient,
	argv1 int64,
	argv2 *comFabricResolvedServicePartitionResult,
	argv3 FabricErrorCode,
) (uintptr, error) {
	panic("not impl")
}
func callStub3930336835(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceGroupFromTemplateDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3947302336(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **comFabricReplicatorSettingsResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub3963299677(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricUpgradeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3983159403(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricPartitionLoadInformationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub3996264914(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeleteNetworkDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4013696870(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4015856684(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricServiceGroupDescriptionResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub4020055637(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedApplicationQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4021168597(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricRepairApproveDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4022021716(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricDeployedServiceTypeQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4029877715(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *FabricServicePartitionAccessStatus,
) (uintptr, error) {
	panic("not impl")
}
func callStub4059762130(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricReplicaSetConfiguration,
) (uintptr, error) {
	panic("not impl")
}
func callStub4080937998(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 ole.GUID,
	argv1 *innerFabricApplicationHealthPolicy,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4093522041(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricProvisionedConfigVersionQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4106038288(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricNameEnumerationResult,
	argv2 bool,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4107741011(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricStateProvider,
	argv1 *innerFabricReplicatorSettings,
	argv2 **comFabricReplicator,
	argv3 **comFabricStateReplicator,
) (uintptr, error) {
	panic("not impl")
}
func callStub4108199174(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricReplicaInformation,
	argv1 *comFabricAsyncOperationCallback,
	argv2 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4148694086(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *uint16,
	argv3 *uint16,
	argv4 *uint16,
) (uintptr, error) {
	panic("not impl")
}
func callStub4149751379(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *innerFabricServiceGroupUpdateDescription,
	argv2 uint32,
	argv3 *comFabricAsyncOperationCallback,
	argv4 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4178191533(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 uint32,
	argv3 *byte,
	argv4 uint32,
	argv5 *comFabricAsyncOperationCallback,
	argv6 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4182969828(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *comFabricServiceGroupFactory,
) (uintptr, error) {
	panic("not impl")
}
func callStub4198895118(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 **innerFabricResolvedServiceEndpoint,
) (uintptr, error) {
	panic("not impl")
}
func callStub4205325366(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceFromTemplateDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4237896764(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricServiceReplicaQueryDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4239265293(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 **comFabricPropertyValueResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub4250938996(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *innerFabricProvisionApplicationTypeDescription,
	argv1 uint32,
	argv2 *comFabricAsyncOperationCallback,
	argv3 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4267384777(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricUpgradeOrchestrationServiceStateResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub4273281094(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetReplicaListResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub4274985020(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetServiceNameResult,
) (uintptr, error) {
	panic("not impl")
}
func callStub4282396229(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *uint16,
	argv1 *uint16,
	argv2 *innerFabricApplicationHealthPolicy,
	argv3 uint32,
	argv4 *comFabricAsyncOperationCallback,
	argv5 **comFabricAsyncOperationContext,
) (uintptr, error) {
	panic("not impl")
}
func callStub4288419927(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 *comFabricAsyncOperationContext,
	argv1 **comFabricGetServiceListResult,
) (uintptr, error) {
	panic("not impl")
}
func createCallbackStub1(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub351017874(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub719329543(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub1252332865(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub2776959849(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub3172535365(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub3267176230(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub3458927767(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub3830844808(
	cb interface{},
) uintptr {
	panic("not impl")
}
