// +build linux,amd64

// Code generated by "go run github.com/tg123/fabric/mkidl"; DO NOT EDIT.
package fabric

import (
	"unsafe"
)

func callStub1(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub96862646(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub142410278(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
) (uintptr, error) {
	panic("not impl")
}
func callStub142934571(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint64,
) (uintptr, error) {
	panic("not impl")
}
func callStub328735686(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 float64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub571021482(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub642392001(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub667092344(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricMoveCost,
) (uintptr, error) {
	panic("not impl")
}
func callStub699991442(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub765140102(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub765920742(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricFaultType,
) (uintptr, error) {
	panic("not impl")
}
func callStub770250917(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub824512273(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub877275087(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1072500600(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 bool,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1121783681(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1128800280(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricStoreBackupOption,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1238898970(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1258170961(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1292376406(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaOpenMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1425410019(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1522013493(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub1580995785(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub1789138364(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaSetQuorumMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2138378508(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2823758008(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 int64,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2844134223(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2876708553(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2937459220(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaRole,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3260095110(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3312394536(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3398245106(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3415612146(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3552647931(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3634565860(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3653833453(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3654885027(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricNodeDeactivationIntent,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3657439995(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3758625517(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3857978088(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3858959655(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3863417581(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3886746928(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3964606417(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricReplicaRole,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub3992725221(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4048098088(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 FabricErrorCode,
) (uintptr, error) {
	panic("not impl")
}
func callStub4076149611(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4095221463(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4096331056(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub4101645460(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4120646493(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4152495520(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func createCallbackStub1(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub699991442(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub2138378508(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub2823758008(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub2844134223(
	cb interface{},
) uintptr {
	panic("not impl")
}
