// +build !windows,!linux,!amd64

// Code generated by "go run github.com/tg123/fabric/mkidl"; DO NOT EDIT.
package fabric

import (
	"unsafe"
)

func callStub1(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub2(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
) (uintptr, error) {
	panic("not impl")
}
func callStub3(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub4(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub5(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub6(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub7(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub8(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 float64,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub9(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub10(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub11(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub12(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub13(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub14(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub15(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub16(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricPartitionKeyType,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub17(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub18(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub19(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 uint32,
	argv6 unsafe.Pointer,
	argv7 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub20(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub21(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricNodeDeactivationIntent,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub22(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub23(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 bool,
	argv1 uint32,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub24(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 uint32,
	argv4 unsafe.Pointer,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub25(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 uint32,
	argv5 unsafe.Pointer,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub26(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub27(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint32,
	argv1 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub28(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 FabricErrorCode,
) (uintptr, error) {
	panic("not impl")
}
func callStub30(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub32(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 uint32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
	argv5 int64,
	argv6 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub36(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricFaultType,
) (uintptr, error) {
	panic("not impl")
}
func callStub37(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricMoveCost,
) (uintptr, error) {
	panic("not impl")
}
func callStub38(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaOpenMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub39(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaRole,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub40(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub41(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub42(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub43(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricReplicaRole,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub44(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 FabricReplicaSetQuorumMode,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub45(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub46(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 unsafe.Pointer,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub47(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 int64,
	argv1 int64,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub48(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub49(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub50(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
) (uintptr, error) {
	panic("not impl")
}
func callStub51(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 FabricStoreBackupOption,
	argv2 unsafe.Pointer,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub52(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub53(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int64,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub54(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 int32,
	argv3 unsafe.Pointer,
	argv4 int64,
	argv5 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub55(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 unsafe.Pointer,
	argv2 bool,
	argv3 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub56(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 unsafe.Pointer,
	argv1 bool,
	argv2 unsafe.Pointer,
) (uintptr, error) {
	panic("not impl")
}
func callStub57(
	addr uintptr,
	argc int,
	this unsafe.Pointer,
	argv0 uint64,
) (uintptr, error) {
	panic("not impl")
}
func createCallbackStub29(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub31(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub33(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub34(
	cb interface{},
) uintptr {
	panic("not impl")
}
func createCallbackStub35(
	cb interface{},
) uintptr {
	panic("not impl")
}
